### PR TITLE
Updating project format to VS2017 and updated nuget packages to latest version

### PR DESCRIPTION
**Pull request by andymac4182**
This is building in VS. I haven't used FAKE before but can check that out as well if that would help.

### CODE REVIEW

**Comment by andymac4182** [comment]
@phatboyg This seems to be ignoring the `appveyor.yml` file that specifies VS2017 and the build script. Do you have a setting at your end that can resolve this?

I have the build mostly working on my fork and it builds in VS correctly https://ci.appveyor.com/project/andymac4182/greenpipes/

**Comment by andymac4182** [comment]
@phatboyg There is a few types missing when I tried to use the netcore version in MassTransit. Is there something being moved around with the next release? They exist in the develop branch but not the netcore one. eg IRequestPipe and RequestContext

**Comment by andymac4182** [comment]
I have rebased and squashed the commits down. The tests are passing for me and all building ok. This has been rebased on the `develop` branch hence the change of base branch and extra commits.

**Comment by phatboyg** [comment]
Dang it's so much less "stuff" with the new csproj format. Looking forward to getting these merged in to unblock MT.

**Pull request closed without merging**
